### ISSUE TITLE
Comment Section

### ISSUE THREAD

**Issue by AryanSahoo-2003** [SR-Sunny-Raj/Hacktoberfest2022-for-all#4]
Hello! As I have seen many of my peers getting stuck at how to add comment section using php ..I want to create a sample website showing a basic comment section..
Can you assign it to me under Hactoberfest ?

**Comment by AryanSahoo-2003** [comment]
sir it is not showing hacktoberfest label...if possible please add it

**Comment by SR-Sunny-Raj** [comment]
Hey @AryanSahoo-2003 actually this repository was also having the same name as the previous one that's why unfortunately it also got excluded and I'm extremely sorry for that. So now you are requested to make your contribution here in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-everyone
